#### Publish on release or pre-release

name: Test the make PR
on: [push, pull_request]

jobs:
  deploy:
    name: Test to do PR
    runs-on: ubuntu-latest
    steps:
      - name: 📤 Checkout the repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: 🎈 Initialize git
        uses: home-assistant/actions/helpers/git-init@master
        with:
          name: GitHub
          email: noreply@github.com
          token: ${{ secrets.HELTO_PAT }}
      - name: 🗄️ Make PR in depdendent repos
        env:
          GITHUB_TOKEN: ${{ secrets.HELTO_PAT }}
          VERSION: "20.52.20"
        run: |
          echo "VERSION: ${VERSION}"
          branch=$(date +%s)
          tempdir="/tmp/a_$branch"
          mkdir "$tempdir"
          cd "$tempdir"
          git clone https://github.com/net-daemon/netdaemon-app-template.git --depth=1
          cd netdaemon-app-template
          git checkout -b "$branch"
          find . -type f -name "*.csproj" -exec sed -i -E "s/(<PackageReference Include=\"JoySoftware\.NetDaemon\.\w*.\" Version=\")(.*)(-beta\".*)/\1${VERSION}\3/g" {} +
          find . -type f -name "*.csproj" -exec git add {} +
          git commit -m "Release ${VERSION}"
          git push --set-upstream origin "$branch"
          gh pr create --fill --title "Release ${VERSION}" --head "$branch"
